package com.egg.servicios.enumeraciones;

public enum Profesiones {

    PLOMERO,
    ELECTRICISTA,
    CERRAJERO,
    CARPINTERO,
    PINTOR,
    JARDINERO,
    LIMPIEZA,
    CLIMATIZACION,
    TECNICO_REFRIGERACION,
    TECNICO_ELECTRODOMESTICO,
    PISCINERO,
    DECORADOR,
    CERAMISTA,
    ALBAÑIL,
    VIDRIERO,
    HERRERO,
    MARMOLERO,
    MODISTA,
    MENSAJERO,
    CATERING_DOMICILIARIO,
    MECANICO,



}